server:
  port: 4444
  
  servlet:
    context-path: '/onlineshop'
    
#MYSQL

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshopPordEnvDB?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:  root     
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update 
    properties:
       hibernate:
            dialect: org.hibernate.dialect.MySQLDialect  
            
 #Management End points        
 
management:
  endpoint:
    health:
      show-details:  always

  endpoints:
    web:
      exposure:
        include:
        - "*"       